import Mathlib.Tactic
import Mathlib.Analysis.InnerProductSpace.PiL2
import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
import Mathlib.MeasureTheory.Constructions.BorelSpace.Order
import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
import ProbabilityTheory.chapter_02.def_2_7


/-

 Definition 2.8  Borel sets in Euclidean space

-/

/-
\begin{defbox}{2.8}
Let $\Omega=\mathbb{R}$ and $\mathcal{C}$ be the collection of all open intervals $(a,b)$, with $a<b$. The $\sigma$-field generated by $\mathcal{C}$ is a $\sigma$-field called the \textit{Borel field}, or the \textit{Borel algebra}, and is written as $\mathcal{B}(\mathbb{R})$. Likewise, for integer $d\ge 1$, we define the Borel algebra $\mathcal{B}(\mathbb{R}^d)$ as the $\sigma$-algebra generated by the open balls in $\mathbb{R}^d$. A set in a Borel algebra is called a \textit{Borel set}.

The Borel algebra $\mathcal{B}(\mathbb{R})$ contains all subsets that we need in practice. For example, closed intervals $[a,b]$ are in $\mathcal{B}(\mathbb{R})$ because it can be expressed as an intersection
\[
[a,b]=\bigcap_{n=1}^{\infty} \left(a-\frac{1}{n},\, b+\frac{1}{n}\right).
\]

Semi-infinite intervals $(-\infty,b]$ are in $\mathcal{B}(\mathbb{R})$ because
\[
(-\infty,b]=\bigcup_{n=1}^{\infty} [b-n,b].
\]

Similarly, $[a,\infty)$, $(a,\infty)$, $(-\infty,b)$, $(a,b]$, $[a,b)$ are Borel sets.
\end{defbox}
-/

open Set MeasureTheory

/-- The collection of all open intervals `(a, b)` in `ℝ`. -/
def realOpenIntervals : Set (Set ℝ) :=
  {S | ∃ a b : ℝ, a < b ∧ S = Set.Ioo a b}

/-- Definition 2.8: the Borel algebra on `ℝ`, generated by open intervals. -/
@[reducible]
def borelAlgebraReal : MeasurableSpace ℝ :=
  generatedSigmaField realOpenIntervals

/-- The collection of open balls in `ℝ^d`. -/
def euclideanOpenBalls (d : ℕ) : Set (Set (EuclideanSpace ℝ (Fin d))) :=
  {S | ∃ c : EuclideanSpace ℝ (Fin d), ∃ r : ℝ, 0 < r ∧ S = Metric.ball c r}

/-- Definition 2.8: the Borel algebra on `ℝ^d`, generated by open balls. -/
@[reducible]
def borelAlgebraEuclidean (d : ℕ) : MeasurableSpace (EuclideanSpace ℝ (Fin d)) :=
  generatedSigmaField (euclideanOpenBalls d)

theorem borelAlgebraReal_eq_borel :
    borelAlgebraReal = borel ℝ := by
  change MeasurableSpace.generateFrom realOpenIntervals = borel ℝ
  apply le_antisymm
  · refine MeasurableSpace.generateFrom_le ?_
    rintro S ⟨a, b, _hab, rfl⟩
    exact measurableSet_Ioo
  · rw [Real.borel_eq_generateFrom_Ioo_rat]
    refine MeasurableSpace.generateFrom_mono ?_
    intro S hS
    simp only [mem_iUnion, mem_singleton_iff] at hS
    rcases hS with ⟨a, b, hab, rfl⟩
    exact ⟨(a : ℝ), (b : ℝ), by exact_mod_cast hab, rfl⟩

theorem closedInterval_mem_borelAlgebraReal (a b : ℝ) :
    @MeasurableSet ℝ borelAlgebraReal (Set.Icc a b) := by
  rw [borelAlgebraReal_eq_borel]
  exact measurableSet_Icc

theorem leftClosedInfinite_mem_borelAlgebraReal (b : ℝ) :
    @MeasurableSet ℝ borelAlgebraReal (Set.Iic b) := by
  rw [borelAlgebraReal_eq_borel]
  exact measurableSet_Iic

theorem rightClosedInfinite_mem_borelAlgebraReal (a : ℝ) :
    @MeasurableSet ℝ borelAlgebraReal (Set.Ici a) := by
  rw [borelAlgebraReal_eq_borel]
  exact measurableSet_Ici

theorem rightOpenInfinite_mem_borelAlgebraReal (a : ℝ) :
    @MeasurableSet ℝ borelAlgebraReal (Set.Ioi a) := by
  rw [borelAlgebraReal_eq_borel]
  exact measurableSet_Ioi

theorem leftOpenInfinite_mem_borelAlgebraReal (b : ℝ) :
    @MeasurableSet ℝ borelAlgebraReal (Set.Iio b) := by
  rw [borelAlgebraReal_eq_borel]
  exact measurableSet_Iio

theorem leftOpenRightClosed_mem_borelAlgebraReal (a b : ℝ) :
    @MeasurableSet ℝ borelAlgebraReal (Set.Ioc a b) := by
  rw [borelAlgebraReal_eq_borel]
  exact measurableSet_Ioc

theorem leftClosedRightOpen_mem_borelAlgebraReal (a b : ℝ) :
    @MeasurableSet ℝ borelAlgebraReal (Set.Ico a b) := by
  rw [borelAlgebraReal_eq_borel]
  exact measurableSet_Ico

/-- # Definition 2.8
Exported definition for Definition 2.8. -/
@[reducible]
def def_2_8 : MeasurableSpace ℝ :=
  borelAlgebraReal
