import Mathlib.Tactic
import Mathlib.MeasureTheory.MeasurableSpace.Pi
-- import Mathlib.Data.Real.Pointwise
import ProbabilityTheory.chapter_02.def_2_8


open Set MeasureTheory MeasurableSpace

open scoped Pointwise

/-- Open `d`-boxes in coordinate form. -/
def openBoxes (d : ℕ) : Set (Set (Fin d → ℝ)) :=
  {s | ∃ a b : Fin d → ℝ,
    (∀ i, a i < b i) ∧ s = Set.pi Set.univ (fun i => Ioo (a i) (b i))}

/-- The real open intervals used in Definition 2.8 cover `ℝ` by a countable
cofinal family. -/
theorem realOpenIntervals_countablySpanning : IsCountablySpanning realOpenIntervals := by
  refine ⟨fun n => Ioo (-(((n + 1 : ℕ) : ℝ))) (((n + 1 : ℕ) : ℝ)), ?_, ?_⟩
  · intro n
    refine ⟨-(((n + 1 : ℕ) : ℝ)), (((n + 1 : ℕ) : ℝ)), ?_, rfl⟩
    have hpos : (0 : ℝ) < ((n + 1 : ℕ) : ℝ) := by
      exact_mod_cast Nat.succ_pos n
    linarith
  · ext x
    constructor
    · intro _; simp
    · intro _
      rcases exists_nat_gt |x| with ⟨n, hn⟩
      refine mem_iUnion.2 ⟨n, ?_⟩
      have hn' : |x| < (((n + 1 : ℕ) : ℝ)) :=
        lt_trans hn (by exact_mod_cast Nat.lt_succ_self n)
      constructor
      · linarith [neg_abs_le x]
      · linarith [le_abs_self x]

/-- Coordinate boxes generated by Definition 2.8's real open intervals are
exactly the textbook open boxes. -/
theorem coordinateOpenBoxes_eq_openBoxes (d : ℕ) :
    Set.pi Set.univ '' Set.pi Set.univ (fun _ : Fin d => realOpenIntervals) =
      openBoxes d := by
  ext s
  constructor
  · rintro ⟨U, hU, rfl⟩
    have hU' : ∀ i : Fin d, U i ∈ realOpenIntervals := by
      intro i
      exact hU i (by simp)
    have hU'' : ∀ i : Fin d, ∃ a b : ℝ, a < b ∧ U i = Ioo a b := by
      intro i
      simpa [realOpenIntervals] using hU' i
    choose a b hab hEq using hU''
    refine ⟨a, b, hab, ?_⟩
    ext x
    simp [hEq]
  · rintro ⟨a, b, hab, rfl⟩
    refine ⟨fun i => Ioo (a i) (b i), ?_, rfl⟩
    intro i _hi
    exact ⟨a i, b i, hab i, rfl⟩

/-- Open `d`-boxes, transported to Mathlib's `EuclideanSpace` model of
`ℝ^d`. -/
def euclideanOpenBoxes (d : ℕ) :
    Set (Set (EuclideanSpace ℝ (Fin d))) :=
  Set.preimage (fun x : EuclideanSpace ℝ (Fin d) => fun i : Fin d => x i) ''
    openBoxes d

/-- The all-positive-radius metric balls form a topological basis in every
pseudo-metric space. -/
theorem metricOpenBalls_isTopologicalBasis {α : Type*} [PseudoMetricSpace α] :
    TopologicalSpace.IsTopologicalBasis
      {S : Set α | ∃ c : α, ∃ r : ℝ, 0 < r ∧ S = Metric.ball c r} := by
  refine TopologicalSpace.isTopologicalBasis_of_isOpen_of_nhds ?_ ?_
  · rintro S ⟨c, r, _hr, rfl⟩
    exact Metric.isOpen_ball
  · intro x U hx hU
    rcases Metric.isOpen_iff.mp hU x hx with ⟨r, hr, hsub⟩
    exact ⟨Metric.ball x r, ⟨x, r, hr, rfl⟩, Metric.mem_ball_self hr, hsub⟩

/-- Supporting Mathlib-facing result: coordinate open boxes generate the usual
Borel sigma-field on `(Fin d → ℝ)`. -/
theorem openBoxes_generateFrom_eq_borel (d : ℕ) :
    MeasurableSpace.generateFrom (openBoxes d) = borel (Fin d → ℝ) := by
  classical
  have hC : ∀ _ : Fin d, MeasurableSpace.generateFrom realOpenIntervals = borel ℝ := by
    intro _
    simpa [borelAlgebraReal] using borelAlgebraReal_eq_borel
  have hboxes :
      MeasurableSpace.generateFrom
          (Set.pi Set.univ '' Set.pi Set.univ (fun _ : Fin d => realOpenIntervals)) =
        MeasurableSpace.pi := by
    exact generateFrom_eq_pi
      (α := fun _ : Fin d => ℝ)
      (C := fun _ : Fin d => realOpenIntervals)
      hC
      (fun _ => realOpenIntervals_countablySpanning)
  rw [← coordinateOpenBoxes_eq_openBoxes d]
  exact hboxes.trans BorelSpace.measurable_eq

/-- Definition 2.8's open balls generate Mathlib's Borel sigma-field on
Euclidean space. -/
theorem euclideanOpenBalls_generateFrom_eq_borel (d : ℕ) :
    MeasurableSpace.generateFrom (euclideanOpenBalls d) =
      borel (EuclideanSpace ℝ (Fin d)) := by
  simpa [euclideanOpenBalls] using
    (metricOpenBalls_isTopologicalBasis
      (α := EuclideanSpace ℝ (Fin d))).borel_eq_generateFrom.symm

/-- Definition 2.8's `borelAlgebraEuclidean` is the usual Borel sigma-field on
Mathlib's Euclidean space. -/
theorem borelAlgebraEuclidean_eq_borel (d : ℕ) :
    borelAlgebraEuclidean d = borel (EuclideanSpace ℝ (Fin d)) := by
  simpa [borelAlgebraEuclidean, generatedSigmaField] using
    euclideanOpenBalls_generateFrom_eq_borel d

/-- Euclidean coordinate boxes generate Mathlib's Borel sigma-field on
`EuclideanSpace ℝ (Fin d)`. -/
theorem euclideanOpenBoxes_generateFrom_eq_borel (d : ℕ) :
    MeasurableSpace.generateFrom (euclideanOpenBoxes d) =
      borel (EuclideanSpace ℝ (Fin d)) := by
  let e : EuclideanSpace ℝ (Fin d) → (Fin d → ℝ) := fun x i => x i
  have hcomap :
      MeasurableSpace.comap e (MeasurableSpace.generateFrom (openBoxes d)) =
        MeasurableSpace.generateFrom (euclideanOpenBoxes d) := by
    simpa [euclideanOpenBoxes, e] using
      (MeasurableSpace.comap_generateFrom (f := e) (s := openBoxes d))
  have hborel :
      borel (EuclideanSpace ℝ (Fin d)) =
        MeasurableSpace.comap e (borel (Fin d → ℝ)) := by
    simpa [e] using
      (borel_comap (α := EuclideanSpace ℝ (Fin d)) (β := Fin d → ℝ)
        (f := e) (t := inferInstance))
  calc
    MeasurableSpace.generateFrom (euclideanOpenBoxes d) =
        MeasurableSpace.comap e (MeasurableSpace.generateFrom (openBoxes d)) :=
      hcomap.symm
    _ = MeasurableSpace.comap e (borel (Fin d → ℝ)) := by
      rw [openBoxes_generateFrom_eq_borel d]
    _ = borel (EuclideanSpace ℝ (Fin d)) :=
      hborel.symm

/-- The textbook open boxes form a topological basis of `ℝ^d`. -/
theorem openBoxes_isTopologicalBasis (d : ℕ) :
    TopologicalSpace.IsTopologicalBasis (openBoxes d) := by
  classical
  refine TopologicalSpace.isTopologicalBasis_of_isOpen_of_nhds ?_ ?_
  · rintro s ⟨a, b, hab, rfl⟩
    exact isOpen_set_pi Set.finite_univ (fun i _ => isOpen_Ioo)
  · intro x U hx hU
    rcases isOpen_pi_iff'.mp hU x hx with ⟨V, hV, hVU⟩
    have hchoose : ∀ i : Fin d,
        ∃ a b : ℝ, a < x i ∧ x i < b ∧ Ioo a b ⊆ V i := by
      intro i
      rcases Metric.isOpen_iff.mp (hV i).1 (x i) (hV i).2 with ⟨r, hr, hball⟩
      refine ⟨x i - r / 2, x i + r / 2, by linarith, by linarith, ?_⟩
      intro y hy
      apply hball
      change dist y (x i) < r
      rw [Real.dist_eq]
      exact abs_lt.mpr ⟨by linarith [hy.1, hr], by linarith [hy.2, hr]⟩
    choose a b ha hb hsub using hchoose
    refine ⟨Set.pi Set.univ (fun i => Ioo (a i) (b i)),
      ⟨a, b, fun i => lt_trans (ha i) (hb i), rfl⟩, ?_, ?_⟩
    · intro i _hi
      exact ⟨ha i, hb i⟩
    · intro y hy
      apply hVU
      intro i hi
      exact hsub i (hy i hi)

/-- The transported open boxes form a topological basis on Mathlib's Euclidean model of `ℝ^d`. -/
theorem euclideanOpenBoxes_isTopologicalBasis (d : ℕ) :
    TopologicalSpace.IsTopologicalBasis (euclideanOpenBoxes d) := by
  let e : EuclideanSpace ℝ (Fin d) ≃L[ℝ] (Fin d → ℝ) :=
    EuclideanSpace.equiv (Fin d) ℝ
  exact (openBoxes_isTopologicalBasis d).isInducing e.toHomeomorph.isInducing

/-- Source-spine direction: every open ball is a countable union of open boxes. -/
theorem euclideanOpenBall_eq_countable_biUnion_openBoxes
    (d : ℕ) (c : EuclideanSpace ℝ (Fin d)) {r : ℝ} (_hr : 0 < r) :
    ∃ S ⊆ euclideanOpenBoxes d, S.Countable ∧
      Metric.ball c r = ⋃ s ∈ S, s := by
  exact (euclideanOpenBoxes_isTopologicalBasis d).exists_countable_biUnion_of_isOpen
    Metric.isOpen_ball

/-- Source-spine direction: every open box is a countable union of open balls. -/
theorem euclideanOpenBox_eq_countable_biUnion_openBalls
    (d : ℕ) {S : Set (EuclideanSpace ℝ (Fin d))}
    (hS : S ∈ euclideanOpenBoxes d) :
    ∃ T ⊆ euclideanOpenBalls d, T.Countable ∧ S = ⋃ t ∈ T, t := by
  have hballBasis :
      TopologicalSpace.IsTopologicalBasis
        {T : Set (EuclideanSpace ℝ (Fin d)) |
          ∃ c : EuclideanSpace ℝ (Fin d), ∃ r : ℝ, 0 < r ∧ T = Metric.ball c r} :=
    metricOpenBalls_isTopologicalBasis (α := EuclideanSpace ℝ (Fin d))
  have hSopen : IsOpen S := (euclideanOpenBoxes_isTopologicalBasis d).isOpen hS
  simpa [euclideanOpenBalls] using hballBasis.exists_countable_biUnion_of_isOpen hSopen

/-- Open balls are measurable for the sigma-field generated by open boxes. -/
theorem euclideanOpenBall_mem_generateFrom_openBoxes
    (d : ℕ) (c : EuclideanSpace ℝ (Fin d)) {r : ℝ} (hr : 0 < r) :
    @MeasurableSet (EuclideanSpace ℝ (Fin d))
      (MeasurableSpace.generateFrom (euclideanOpenBoxes d)) (Metric.ball c r) := by
  rcases euclideanOpenBall_eq_countable_biUnion_openBoxes d c hr with
    ⟨S, hSsub, hScount, hEq⟩
  rw [hEq]
  exact MeasurableSet.biUnion hScount fun s hs =>
    measurableSet_generateFrom (hSsub hs)

/-- Open boxes are measurable for the sigma-field generated by open balls. -/
theorem euclideanOpenBox_mem_generateFrom_openBalls
    (d : ℕ) {S : Set (EuclideanSpace ℝ (Fin d))}
    (hS : S ∈ euclideanOpenBoxes d) :
    @MeasurableSet (EuclideanSpace ℝ (Fin d))
      (MeasurableSpace.generateFrom (euclideanOpenBalls d)) S := by
  rcases euclideanOpenBox_eq_countable_biUnion_openBalls d hS with
    ⟨T, hTsub, hTcount, hEq⟩
  rw [hEq]
  exact MeasurableSet.biUnion hTcount fun t ht =>
    measurableSet_generateFrom (hTsub ht)

/-- # Theorem 2.8
the Borel algebra on `ℝ^d`, introduced in Definition 2.8
from open balls, is generated by open `d`-dimensional boxes. -/
theorem thm_2_8 (d : ℕ) :
    MeasurableSpace.generateFrom (euclideanOpenBoxes d) =
      borelAlgebraEuclidean d := by
  change MeasurableSpace.generateFrom (euclideanOpenBoxes d) =
    MeasurableSpace.generateFrom (euclideanOpenBalls d)
  apply le_antisymm
  · exact MeasurableSpace.generateFrom_le fun S hS =>
      euclideanOpenBox_mem_generateFrom_openBalls d hS
  · refine MeasurableSpace.generateFrom_le ?_
    rintro S ⟨c, r, hr, rfl⟩
    exact euclideanOpenBall_mem_generateFrom_openBoxes d c hr
