import Mathlib.Tactic
import Mathlib.MeasureTheory.Measure.MeasureSpace

/-

 Theorem 2.6 sigma-algebra generated by a collection of sets

-/

/-
\begin{thmbox}{2.6}
Let $\mathcal{C}$ be a collection of subsets in $\Omega$, and $\mathcal{F}$ be
the intersection of all $\sigma$-fields that contain $\mathcal{C}$ as a sub-collection. Then $\mathcal{F}$ is a $\sigma$-field, and it is the smallest $\sigma$-field that contains $\mathcal{C}$.
\end{thmbox}

\textit{Proof} We can write $\mathcal{F}$ as
\[
\mathcal{F}
=
\bigcap_{\mathcal{H}:\sigma\text{-field},\ \mathcal{C}\subseteq \mathcal{H}} \mathcal{H},
\]
where the intersection taken over all $\sigma$-fields that contain $\mathcal{C}$ as a sub-collection. The intersection is not empty because $\mathcal{P}(\Omega)$ is such a $\sigma$-field. We next check that $\mathcal{F}$ is a $\sigma$-field.

To show that $\mathcal{F}$ is a $\sigma$-field, we need to verify the three axioms:
\begin{itemize}
    \item $\Omega\in \mathcal{F}$ because $\Omega$ is an element of every $\sigma$-field, in particular, every $\sigma$-field that contains $\mathcal{C}$.
    \item If $A\in \mathcal{F}$, then $A$ is contained in every $\sigma$-field that contains $\mathcal{C}$. Since any $\sigma$-field is closed under taking complements, $A^c$ is also contained in every $\sigma$-field that contains $\mathcal{C}$. This proves that $A^c\in \mathcal{F}$.
    \item Suppose $A_i\in \mathcal{F}$, for $i=1,2,\dots$. By definition, $A_i$ is contained in every $\sigma$-field that contains $\mathcal{C}$, so their union $\cup_i A_i$ is also contained in every $\sigma$-field containing $\mathcal{C}$. Therefore $\cup_i A_i$ is an element of $\mathcal{F}$.
\end{itemize}

This proves that $\mathcal{F}$ is a $\sigma$-field that contains $\mathcal{C}$. Moreover, if $\mathcal{G}$ is any $\sigma$-field that contains $\mathcal{C}$, then $\mathcal{G}$ is one of the $\sigma$-fields being intersected to form $\mathcal{F}$. Therefore, $\mathcal{F}$ is a subset of $\mathcal{G}$. This implies that $\mathcal{F}$ is the smallest $\sigma$-field containing $\mathcal{C}$. \hfill $\square$
-/


open Set MeasureTheory

/-- A sigma-field on `Ω` contains the source collection `C`. -/
def SigmaFieldContains {Ω : Type*} (C : Set (Set Ω)) (F : MeasurableSpace Ω) : Prop :=
  ∀ s ∈ C, @MeasurableSet Ω F s

/--
The source intersection construction: a set belongs to the intersection iff it is
measurable in every sigma-field that contains `C`.
-/
def sigmaFieldIntersection {Ω : Type*} (C : Set (Set Ω)) : Set (Set Ω) :=
  {s | ∀ F : MeasurableSpace Ω, SigmaFieldContains C F → @MeasurableSet Ω F s}

/-- The indexing family is nonempty: the discrete sigma-field contains every set. -/
lemma sigmaFieldsContaining_nonempty {Ω : Type*} (C : Set (Set Ω)) :
    ∃ F : MeasurableSpace Ω, SigmaFieldContains C F := by
  refine ⟨⊤, ?_⟩
  intro s hs
  trivial

/-- The intersection contains `Ω`, since every sigma-field contains `Ω`. -/
lemma sigmaFieldIntersection_univ {Ω : Type*} (C : Set (Set Ω)) :
    Set.univ ∈ sigmaFieldIntersection C := by
  intro F hF
  exact MeasurableSet.univ

/-- The intersection is closed under complements. -/
lemma sigmaFieldIntersection_compl {Ω : Type*} (C : Set (Set Ω)) {A : Set Ω}
    (hA : A ∈ sigmaFieldIntersection C) : Aᶜ ∈ sigmaFieldIntersection C := by
  intro F hF
  exact (hA F hF).compl

/-- The intersection is closed under countable unions. -/
lemma sigmaFieldIntersection_iUnion {Ω : Type*} (C : Set (Set Ω)) {A : ℕ → Set Ω}
    (hA : ∀ n, A n ∈ sigmaFieldIntersection C) :
    (⋃ n, A n) ∈ sigmaFieldIntersection C := by
  intro F hF
  exact MeasurableSet.iUnion (fun n => hA n F hF)

/-- The intersection contains the original collection `C`. -/
lemma sigmaFieldIntersection_contains {Ω : Type*} (C : Set (Set Ω)) {A : Set Ω}
    (hA : A ∈ C) : A ∈ sigmaFieldIntersection C := by
  intro F hF
  exact hF A hA

/-- The intersection is contained in every sigma-field that contains `C`. -/
lemma sigmaFieldIntersection_minimal {Ω : Type*} (C : Set (Set Ω))
    (F : MeasurableSpace Ω) (hF : SigmaFieldContains C F) :
    ∀ A, A ∈ sigmaFieldIntersection C → @MeasurableSet Ω F A := by
  intro A hA
  exact hA F hF

/-- The source intersection construction is itself a measurable space. -/
@[reducible]
def intersectionMeasurableSpace {Ω : Type*} (C : Set (Set Ω)) : MeasurableSpace Ω where
  MeasurableSet' := sigmaFieldIntersection C
  measurableSet_empty := by
    intro F hF
    exact MeasurableSet.empty
  measurableSet_compl := by
    intro A hA F hF
    exact (hA F hF).compl
  measurableSet_iUnion := by
    intro A hA F hF
    exact MeasurableSet.iUnion (fun n => hA n F hF)

/-- The explicit intersection construction agrees with Mathlib's generated sigma-field. -/
lemma intersectionMeasurableSpace_eq_generateFrom {Ω : Type*} (C : Set (Set Ω)) :
    intersectionMeasurableSpace C = MeasurableSpace.generateFrom C := by
  apply le_antisymm
  · intro A hA
    exact hA (MeasurableSpace.generateFrom C)
      (fun s hs => MeasurableSpace.GenerateMeasurable.basic s hs)
  · exact MeasurableSpace.generateFrom_le
      (fun A hA => sigmaFieldIntersection_contains C hA)

/--
Concrete source proof spine for Theorem 2.6: the indexing family is nonempty, the
intersection satisfies the sigma-field closure checks, it contains `C`, and it is
minimal among sigma-fields containing `C`.
-/
theorem thm_2_6_intersection_spine {Ω : Type*} (C : Set (Set Ω)) :
    (∃ F : MeasurableSpace Ω, SigmaFieldContains C F) ∧
      Set.univ ∈ sigmaFieldIntersection C ∧
      (∀ A, A ∈ sigmaFieldIntersection C → Aᶜ ∈ sigmaFieldIntersection C) ∧
      (∀ A : ℕ → Set Ω, (∀ n, A n ∈ sigmaFieldIntersection C) →
        (⋃ n, A n) ∈ sigmaFieldIntersection C) ∧
      (∀ A ∈ C, A ∈ sigmaFieldIntersection C) ∧
      ∀ F : MeasurableSpace Ω, SigmaFieldContains C F →
        ∀ A, A ∈ sigmaFieldIntersection C → @MeasurableSet Ω F A := by
  exact ⟨
    sigmaFieldsContaining_nonempty C,
    sigmaFieldIntersection_univ C,
    fun A hA => sigmaFieldIntersection_compl C hA,
    fun A hA => sigmaFieldIntersection_iUnion C hA,
    fun A hA => sigmaFieldIntersection_contains C hA,
    fun F hF A hA => sigmaFieldIntersection_minimal C F hF A hA⟩

/--  # Theorem 2.6
The sigma-field generated by `C` contains `C`, and it is contained in every
sigma-field that contains `C`. The proof routes through the explicit intersection
construction above, so the source proof spine is available as named landings.
-/
theorem thm_2_6 {Ω : Type*} (C : Set (Set Ω)) :
    (∀ s ∈ C, @MeasurableSet Ω (MeasurableSpace.generateFrom C) s) ∧
      ∀ F : MeasurableSpace Ω, (∀ s ∈ C, @MeasurableSet Ω F s) →
        ∀ s, @MeasurableSet Ω (MeasurableSpace.generateFrom C) s → @MeasurableSet Ω F s := by
  have h_eq : intersectionMeasurableSpace C = MeasurableSpace.generateFrom C :=
    intersectionMeasurableSpace_eq_generateFrom C
  refine ⟨?_, ?_⟩
  · intro s hs
    have hs_inter : s ∈ sigmaFieldIntersection C := sigmaFieldIntersection_contains C hs
    rw [← h_eq]
    exact hs_inter
  · intro F hF s hs
    have hs_inter : @MeasurableSet Ω (intersectionMeasurableSpace C) s := by
      rwa [h_eq]
    exact sigmaFieldIntersection_minimal C F hF s hs_inter
