import Mathlib.Tactic
import Mathlib.MeasureTheory.MeasurableSpace.Defs
import Mathlib.MeasureTheory.Measure.MeasureSpaceDef

/-

  # Definition 8.3 Measurable rectangle

-/


/-
\begin{defbox}{8.3}
Let $(\mathcal{X},\mathcal{F})$ and $(\mathcal{Y},\mathcal{G})$ be measurable spaces. For any $E_1\in \mathcal{F}$ and $E_2\in \mathcal{G}$, the Cartesian product $E_1\times E_2$ is called a \textit{measurable rectangle}. We use the notation $\mathcal{F}\times \mathcal{G}$ to represent the $\sigma$-field generated by all the measurable rectangles.

The $\sigma$-field $\mathcal{F}\times \mathcal{G}$ is the smallest $\sigma$-field containing all measurable rectangles. However, not all sets in $\mathcal{F}\times \mathcal{G}$ are of the form $E_1\times E_2$ with $E_1\in \mathcal{F}$ and $E_2\in \mathcal{G}$. For example, the countable union of measurable rectangles is also in $\mathcal{F}\times \mathcal{G}$. Thus, there are many sets in $\mathcal{F}\times \mathcal{G}$ that are not themselves measurable rectangles.
\end{defbox}
-/

open Set

/-- A measurable rectangle in the product of two measurable spaces. -/
def MeasurableRectangle
    {α β : Type*} [MeasurableSpace α] [MeasurableSpace β]
    (E₁ : Set α) (E₂ : Set β) : Set (α × β) :=
  E₁ ×ˢ E₂

/-- The family of all measurable rectangles. -/
def MeasurableRectangles
    {α β : Type*} [MeasurableSpace α] [MeasurableSpace β] : Set (Set (α × β)) :=
  {s | ∃ E₁ : Set α, ∃ E₂ : Set β, MeasurableSet E₁ ∧ MeasurableSet E₂ ∧
      s = MeasurableRectangle E₁ E₂}

/-- The product sigma-field generated by measurable rectangles. Lean's product measurable space
is the textbook `𝓕 × 𝓖`. -/
@[reducible]
def ProductSigmaField
    {α β : Type*} [MeasurableSpace α] [MeasurableSpace β] : MeasurableSpace (α × β) :=
  inferInstance

/-- Any measurable rectangle is measurable in the product sigma-field. -/
theorem measurableRectangle_measurable
    {α β : Type*} [MeasurableSpace α] [MeasurableSpace β]
    {E₁ : Set α} {E₂ : Set β}
    (hE₁ : MeasurableSet E₁) (hE₂ : MeasurableSet E₂) :
    MeasurableSet (MeasurableRectangle E₁ E₂) := by
  exact hE₁.prod hE₂

/-- Exported definition for Definition 8.3. -/
@[reducible]
def def_8_3
    {α β : Type*} [MeasurableSpace α] [MeasurableSpace β] : MeasurableSpace (α × β) :=
  ProductSigmaField
