import Mathlib.Tactic
import Mathlib.MeasureTheory.Measure.MeasureSpaceDef

/-

  # Definition 5.3 sigma-algebra generated by a random variable

The notation in the book is σ(X)

-/

@[reducible]
def def_5_3 {Ω β : Type _}
  [MeasurableSpace Ω] [MeasurableSpace β] (X : Ω → β) :
    MeasurableSpace Ω :=
  MeasurableSpace.comap X inferInstance
