import Mathlib.Tactic
import ProbabilityTheory.chapter_05.def_5_2
import ProbabilityTheory.chapter_05.def_5_3
import ProbabilityTheory.chapter_05.def_5_4

/--

 ## Theorem 5.1

Two random variables X and Y are independent iff the
sigma-algebras generated by X and Y are independent.
-/
theorem thm_5_1 {Ω β γ : Type _} [MeasurableSpace Ω] [MeasurableSpace β] [MeasurableSpace γ]
    (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsZeroOrProbabilityMeasure μ]
    (X : Ω → β) (Y : Ω → γ) :
    def_5_2 μ X Y ↔
      def_5_4 μ {s | @MeasurableSet Ω (def_5_3 X) s} {t | @MeasurableSet Ω (def_5_3 Y) t} := by
  simpa [def_5_2, def_5_3, def_5_4] using
    (ProbabilityTheory.IndepFun_iff_Indep X Y μ).trans
      (ProbabilityTheory.Indep_iff_IndepSets _ _ μ)
