import Mathlib.Tactic
import Mathlib.Probability.Independence.ZeroOne

/-

 # Theorem 5.11 Kolmogorov 0-1 law

-/

/-
\begin{theorem}[Kolmogorov's Zero--One Law]
Let $(X_n)_{n=1}^\infty$ be a sequence of random variables, and define the tail $\sigma$-algebra by $\mathcal{T} \triangleq \bigcap_{n=1}^{\infty} \sigma(\{X_i:i\ge n\})$. If the random variables $X_n$, for $n\ge 1$, are mutually independent, then any event in the tail $\sigma$-algebra has probability equal to either $0$ or $1$.
\end{theorem}

\begin{proof}
The idea of proof is to show that the tail $\sigma$-algebra $\mathcal{T}$ is independent of itself. Let $\mathcal{G}_n$ denote the $\sigma$-algebra generated by the first $n$ random variables $X_1,\dots,X_n$ in the sequence. The $\sigma$-algebra $\mathcal{G}_n$ is independent of the tail $\sigma$-algebra $\mathcal{T}$, because any event in $\mathcal{T}$ is in $\sigma(\{X_i:i>n\})$, which is independent with $\mathcal{G}_n$.
\end{proof}
-/

-- WRITE FINAL LEAN CODE BELOW
open Filter

/- The tail σ-algebra of a sequence of random variables. -/
@[reducible]
def tailSigmaAlgebra {Ω β : Type*} [MeasurableSpace Ω] [MeasurableSpace β]
    (X : ℕ → Ω → β) : MeasurableSpace Ω :=
  limsup (fun n => MeasurableSpace.comap (X n) ‹MeasurableSpace β›) atTop

/--  ## Theorem 5.11
Kolmogorov's zero-one law for a sequence of independent random variables.

The tail σ-algebra is encoded as the `limsup` of the σ-algebras generated by the
coordinate maps `X n`, which matches the textbook description
`⋂ n σ({X_i : i ≥ n})`.
-/
theorem thm_5_11 {Ω β : Type*} [MeasurableSpace Ω] [MeasurableSpace β]
    (P : MeasureTheory.Measure Ω) [MeasureTheory.IsProbabilityMeasure P]
    (X : ℕ → Ω → β) (h_meas : ∀ n, Measurable (X n))
    (h_indep : ProbabilityTheory.iIndepFun X P) {t : Set Ω}
    (ht_tail : @MeasurableSet Ω (tailSigmaAlgebra X) t) :
    P t = 0 ∨ P t = 1 := by
  let s : ℕ → MeasurableSpace Ω := fun n => MeasurableSpace.comap (X n) ‹MeasurableSpace β›
  have h_le : ∀ n, s n ≤ ‹MeasurableSpace Ω› := fun n => (h_meas n).comap_le
  simpa [s, tailSigmaAlgebra] using
    ProbabilityTheory.measure_zero_or_one_of_measurableSet_limsup_atTop
      (μ := P) h_le h_indep.iIndep ht_tail
