import ProbabilityTheory.chapter_03.def_3_1
import Mathlib.MeasureTheory.Measure.MeasureSpace

open MeasureTheory ENNReal

/--  # Definition 3.2
Suppose μ₀ is a pre-measure defined on a field ℱ₀, and let ℱ be the σ-field
generated by ℱ₀. We say that μ : ℱ → [0, ∞] is an extension of μ₀ if μ is a measure and satisfies
μ(E) = μ₀(E) for all E ∈ ℱ₀.

According to the provided logical conditions:
1. Measure Property: μ is a valid measure on the measurable space (X, ℱ).
2. Agreement on the Base Field: For every subset E ⊆ X such that E ∈ ℱ₀, μ(E) = μ₀(E).
-/
def IsExtension {X : Type*} (F₀ : Set (Set X)) (μ₀ : Set X → ℝ≥0∞)
    (μ : @Measure X (MeasurableSpace.generateFrom F₀)) : Prop :=
  ∀ E ∈ F₀, μ E = μ₀ E
