import Mathlib.Tactic
import ProbabilityTheory.chapter_03.def_3_1
import ProbabilityTheory.chapter_03.def_3_2

/-!
# Carathéodory Extension Theorem: existence

The project's `Premeasure` is first exposed as Mathlib's `AddContent`.  Mathlib's
Carathéodory extension API then constructs the measure on the generated sigma-field.
Uniqueness is stated after Theorem 3.8, where the needed pi-lambda argument is available.
-/

open Set MeasureTheory ENNReal

/-- **Theorem 3.1 (existence part).** A pre-measure on a field of sets extends to a
measure on the sigma-field generated by that field. -/
theorem thm_3_1 {X : Type u} (F₀ : FieldOfSets X) (pm : Premeasure F₀) :
    ∃ μ : @Measure X (MeasurableSpace.generateFrom F₀.carrier),
      IsExtension F₀.carrier pm.toSetFunction μ := by
  letI : MeasurableSpace X := MeasurableSpace.generateFrom F₀.carrier
  let μ : Measure X :=
    pm.toAddContent.measure F₀.isSetRing.isSetSemiring le_rfl
      pm.toAddContent_isSigmaSubadditive
  refine ⟨μ, ?_⟩
  intro s hs
  calc
    μ s = pm.toAddContent s :=
      AddContent.measure_eq pm.toAddContent F₀.isSetRing.isSetSemiring rfl
        pm.toAddContent_isSigmaSubadditive hs
    _ = pm.toSetFunction s := rfl
