import Mathlib.MeasureTheory.MeasurableSpace.Basic

/-!
# Formalization of Measurability via Generating Sets

This theorem proves that a function f : (Ω, ℱ) → (Ω', 𝒢) is measurable if and only if
the preimage of every set in a generating collection C for 𝒢 is measurable in ℱ.
-/

section Theorem_4_4

open MeasureTheory Set

universe u v

variable {Ω : Type u} {Ω' : Type v}

/--   ## Theorem 4.4
Let f : Ω → Ω' be a function. Let (Ω, ℱ) be a measurable space and
let 𝒢 be the σ-algebra on Ω' generated by a collection C.
Then f is (ℱ, 𝒢)-measurable iff for all A ∈ C, f⁻¹(A) is measurable in ℱ.
-/
theorem measurable_iff_preimage_generating_set
    [mF : MeasurableSpace Ω]
    {C : Set (Set Ω')}
    (f : Ω → Ω') :
    @Measurable Ω Ω' mF (MeasurableSpace.generateFrom C) f ↔
    ∀ A ∈ C, MeasurableSet (f ⁻¹' A) := by
  constructor
  · -- Forward direction: If f is measurable, then f⁻¹(A) is measurable for A ∈ C.
    intro hf A hA
    -- Since f is measurable, the preimage of any set measurable in σ(C) is measurable in ℱ.
    -- We apply the definition of measurability to A.
    apply hf
    -- In the σ-algebra generated by C, every element of C is measurable.
    exact MeasurableSpace.measurableSet_generateFrom hA

  · -- Backward direction: If preimages of generators are measurable, f is measurable.
    intro hA
    -- Mathlib's `measurable_generateFrom` is specifically designed for this.
    -- It states that if preimages of a generating set are measurable, the function is measurable.
    apply measurable_generateFrom
    exact hA

/--
Alternative statement: If the target space already has a MeasurableSpace instance 𝒢
that is equal to the one generated by C.
-/
example
    [mF : MeasurableSpace Ω]
    [mG : MeasurableSpace Ω']
    {C : Set (Set Ω')}
    (hG : mG = MeasurableSpace.generateFrom C)
    (f : Ω → Ω') :
    Measurable f ↔ ∀ A ∈ C, MeasurableSet (f ⁻¹' A) := by
  -- Use the equality to substitute the generated σ-algebra for mG.
  rw [hG]
  exact measurable_iff_preimage_generating_set f

end Theorem_4_4
